### ISSUE TITLE
PHP Fatal Error: Uncaught Error: Can only throw objects

### ISSUE THREAD

**Issue by GaryJones** [microsoft/bing-wordpress-url-submission-plugin#12]
> Uncaught Error: Can only throw objects

[This line](https://github.com/microsoft/bing-wordpress-url-submission-plugin/blob/d2381b1a18ab25f599cdf446148a54b02ff47422/public/admin/utils/class-bing-url-submission-admin-routes.php#L303) is using `throw` with a string, and that's not valid in PHP.

**Comment by lrehmann** [comment]
same issue over here:

`WordPress version 5.7
Current theme: Twenty Nineteen (version 1.9)
Current plugin: Bing Webmaster Url Submission (version 1.0.9)
PHP version 7.3.27

Error Details
=============
An error of type E_ERROR was caused in line 303 of the file /mnt/xxx/wp-content/plugins/bing-webmaster-tools/admin/utils/class-bing-url-submission-admin-routes.php. Error message: Uncaught Error: Can only throw objects in /mnt/xxx/wp-content/plugins/bing-webmaster-tools/admin/utils/class-bing-url-submission-admin-routes.php:303
Stack trace:
#0 /mnt/xxx/wp-content/plugins/bing-webmaster-tools/admin/class-bing-url-submission-admin.php(193): Bing_Webmaster_Admin_Routes->submit_url_to_bwt('https://xxx...', 'https://xxx...', 'xxx...', 'update', false)
#1 /mnt/xxx/wp-includes/class-wp-hook.php(292): Bing_Webmaster_Admin->on_post_published('publish', 'publish', Object(WP_Post))
#2 /mnt/xxx/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#3 /mnt/xxx/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /mnt/xxx/wp-includes/post.php(5014): do_action('transition_post...', 'publish', 'publish', Object(WP_Post))
#5 /mnt/xxx/wp-includes/post.php(4284): wp_transition_post_status('publish', 'publish', Object(WP_Post))
#6 /mnt/xxx/wp-includes/post.php(4486): wp_insert`

**Comment by GaryJones** [comment]
@nevinvalsaraj @microsoftopensource What's the timeframe for this to be acknowledged and fixed?

**Comment by nevinvalsaraj** [comment]
@SouriChalla @sairagh

**Comment by sairagh** [comment]
hi @GaryJones , we have fixed the issue and released it.

**Comment by GaryJones** [comment]
Thanks!

For other folks' reference:

- [Inital fix](https://github.com/microsoft/bing-wordpress-url-submission-plugin/commit/7dc055c1121442aa12928aded972b0de0f5d96d4#diff-c92bfb5ca032860f211be98053dc0561675d2128d435e415be48d0022dfa4069)
- [Extra fix to make logging errors conditional to WP_DEBUG](https://github.com/microsoft/bing-wordpress-url-submission-plugin/commit/3d0b97a5a2049b0f6dd9c72f50facaf6a765abcf#diff-c92bfb5ca032860f211be98053dc0561675d2128d435e415be48d0022dfa4069)
