### ISSUE TITLE
Updating to the latest version 1.0.11 causes critical error that breaks dashboard if WP Core is < 5.7

### ISSUE THREAD

**Issue by tpolischuk** [microsoft/bing-wordpress-url-submission-plugin#19]
There is a call to an undefined function (is_post_publicly_viewable()) for WP installs that are < 5.7. This causes the entire dashboard to break. I am guessing this needs to wrapped in a is_defined check or something similar to prevent this from crashing sites.

**Comment by pingal** [comment]
@tpolischuk Thanks for raising the issue. We will release a fix soon.

**Comment by pingal** [comment]
fixed in version 1.0.12
