### ISSUE TITLE
Can not submit API key

### ISSUE THREAD

**Issue by DanielDolhy** [microsoft/bing-wordpress-url-submission-plugin#33]
Hello, please can you help me to solve this one? When I submit the API key and hit the "Start using plugin" button nothing happens and I get the error in console: **Uncaught (in promise) TypeError: Cannot read property 'length' of undefined at StartPage.tsx:21** 

Thank you very much in advance

**Comment by martin-badin** [comment]
The issue is on this line
https://github.com/microsoft/bing-wordpress-url-submission-plugin/blob/main/src/components/StartPage.tsx#L21

I was debugging the issue and found that `error_type` doesn't exist in the `data` object.
```json
{
    "data": {
        "hasAPIKey": false
    }
}
```
