### ISSUE TITLE
Submits non-public URLs

### ISSUE THREAD

**Issue by BrianHenryIE** [microsoft/bing-wordpress-url-submission-plugin#7]
A plugin I use uses a custom post type to save data. When the post is created Bing URL Submissions Plugin sends the URL of that post to Bing to be indexed. The URL returns 404 to the public.

Please test the URLs before submission with ~ `wp_remote_head()`.

Otherwise the submission API quota is wasted.

I think this solves the ticket raised at: [Random URL being submitted to Bing](https://wordpress.org/support/topic/random-url-being-submitted-to-bing/).

**Comment by pingal** [comment]
fixed in version 1.0.11
